### ISSUE TITLE
오타신고 ( '자바스크립트의 상위집' -> '자바스크립트의 상위집합' )

### ISSUE THREAD

**Issue by jayonthegreen** [heejongahn/ts-for-jsdev#1]
오타신고합니다.

https://ahnheejong.gitbook.io/ts-for-jsdev/01-introducing-typescript/intro 

'자바스크립트의 상위집' -> '자바스크립트의 상위집합'  인것 같습니다.

좋은 자료 공유 감사합니다.

**Comment by heejongahn** [comment]
감사합니다!
