### ISSUE TITLE
Report typos

### ISSUE THREAD

**Issue by gunwooterry** [heejongahn/ts-for-jsdev#10]
2.4.2 문자열 치환의 마지막 코드 블럭 5째 줄에 `{lastName}`을 `${lastName}`으로 수정해야 합니다.

**Comment by gunwooterry** [comment]
새로운 이슈를 열기보다 일단은 여기에 추가하겠습니다.

2.5.2에 다음과 같은 설명이 있습니다.
`for (const elem in obj) { ... }` 에서 `elem`은 항상 문자열인 반면, `for (const elem in arr) { ... }` 의 elem은 임의의 타입일 수 있다.

* `for-in`과 다른 `for-of`의 특징을 설명하면서 해당 문장이 나오는데, `for-of`의 특징을 설명하는 문맥에도 어울리지 않는 것 같고, 어떤 의도인지도 잘 와닿지 않습니다. `for-in` 문법이 오브젝트와 배열에 대해 각각 다르게 작동한다는 것이 요점인가요?
* 콤마 뒤에 나오는 elem이 `elem`이 되어야 합니다.

**Comment by heejongahn** [comment]
안녕하세요. 오타 제보 감사드립니다.

`for-in` 과 `for-of`의 차이점을 설명하는 부분에서는 제가 완전히 엉뚱한 예제를 든 것이 맞습니다 ㅜㅜ 찾아내주셔서 감사합니다. 차이점은, `for-in`의 경우 멤버의 키에 해당하는 문자열을 바인딩합니다. 반면, `for-of` 에서는 실제 멤버값을 바인딩합니다. 아래 예제를 보시면 무슨 뜻인지 바로 알 수 있을 것 같습니다. 

```js
const arr = [function() { console.log('42'); }];

for (const elem in arr) {
  console.log(typeof elem);
}
// string

for (const elem of arr) {
  console.log(typeof elem);
}
// function

for (const elem in arr) {
  elem();
}
// TypeError: elem is not a function

for (const elem of arr) {
  elem();
}
// 42
```

이 이슈는 예제를 좀 더 잘 이해할 수 있도록 수정하고 닫겠습니다.

**Comment by heejongahn** [comment]
반영했습니다 https://ahnheejong.gitbook.io/ts-for-jsdev/02-ecmascript/element-enumeration/for-of.
