### ISSUE TITLE
Ommitted closing parentheses 

### ISSUE THREAD

**Issue by marocchino** [heejongahn/ts-for-jsdev#11]
https://github.com/heejongahn/ts-for-jsdev/blob/775afd20d8bbb63b1e5984a8a6b6be0195b2afc0/03-basic-grammar/generics.md#L13-L18
https://github.com/heejongahn/ts-for-jsdev/blob/775afd20d8bbb63b1e5984a8a6b6be0195b2afc0/03-basic-grammar/generics.md#L31-L33

**Comment by heejongahn** [comment]
Closed by 20f6015b3dcc217e5ba194568af23869f8700cbf.
