### ISSUE TITLE
[2.1.1] let을 이용한 선언

### ISSUE THREAD

**Issue by jbee37142** [heejongahn/ts-for-jsdev#14]
희종님 :) ts-for-jsdev 라는 정말 훌륭한 자료 감사합니다! 정독 중, 제 판단하에 독자로 하여금 잘못 해석될 수 있는 정보가 있는 것 같아 이렇게 이슈를 남겨봅니다 :)

`let으로 선언한 변수는 호이스팅 되지 않는다.` 

위 구문에 대한 내용인데요, '호이스팅'이라는 용어를 어떻게 정의하느냐, 즉 여러 의미를 내포한 호이스팅으로 정의하느냐에 따라 올바른 내용이 될 수도 있다고 생각합니다. 하지만, 아래 내용를 보았을 때, `let` 또는 `const` 키워드를 사용하여 변수를 선언했을 때도 마찬가지로 **호이스팅은 됩니다.**

> **NOTE** `let` and `const` declarations define variables that are scoped to [the running execution context](https://www.ecma-international.org/ecma-262/6.0/#sec-execution-contexts)’s [LexicalEnvironment](https://www.ecma-international.org/ecma-262/6.0/#sec-execution-contexts). The variables are created when their containing [Lexical Environment](https://www.ecma-international.org/ecma-262/6.0/#sec-lexical-environments) is instantiated but may not be accessed in any way until the variable’s LexicalBinding is evaluated. A variable defined by a LexicalBinding with an Initializer is assigned the value of its *Initializer*’s AssignmentExpression when the LexicalBinding is evaluated, not when the variable is created. If a LexicalBinding in a `let` declaration does not have an Initializer the variable is assigned the value **undefined** when the LexicalBinding is evaluated.

_Reference : https://www.ecma-international.org/ecma-262/6.0/#sec-let-and-const-declarations_

`hoisting`은 브라우저가 자바스크립트를 파싱하는 단계에서 어느 정도의 메모리를 확보해야 겠다는 것을 측정하기 위해 발생하는 단계입니다.(https://developer.mozilla.org/en-US/docs/Glossary/Hoisting)

`var` 키워드로 선언한 변수와 달리, `let`과 `const`로 선언한 변수를 선언하기 전에 참조하지 못하는 것은 hoisting이 발생하지 않아서 접근하지 못하는 것이 아니라 `TDZ(Temporary Dead Zone)`이라는 영역 때문입니다. 스펙 문서에서는 이를 `not be accessed in any way until the variable’s LexicalBinding is evaluated` 로 표현했습니다.

위 링크처럼 스펙 문서는 아니지만 `Temporary Dead Zone`에 대해 잘 설명해둔 article이 있어 첨부합니다 :)
- http://jsrocks.org/2015/01/temporal-dead-zone-tdz-demystified

해당 이슈를 올리면서도 TypeScript를 다루고 있는 GitBook에서 ECMAScript에 대해 너무 미시적으로 접근하는 것은 아닌가 하는 걱정이 있네요. 하지만 국내 많은 저서와 너무 많은 블로그 글들이 스펙에 기반하지 않고 `호이스팅이 되지 않는다.`라고 명시하고 있어서 여기에서 만큼은 스펙에 정의된 대로 설명이 되었으면 해서 이슈를 남겨보았습니다.

ts-for-jsdev 계속 응원하겠습니다!!

**Comment by heejongahn** [comment]
재엽님 제가 이거 못 본 것은 아닌데 정성스럽게 써주신 만큼 제대로 읽고 처리하는 게 맞는 것 같아 짬 + 정신적 여유가 날 때까지 방치(?)하고 있습니다. 너무 감사드리고, 이번주 내로는 꼭 피드백 드릴게요!

**Comment by jbee37142** [comment]
@heejongahn 천천히 주셔도 됩니다~ 감사합니다😄

**Comment by heejongahn** [comment]
말씀드린 것보다 훨씬 늦어졌지만 😢 반영했습니다. 다시 한 번 감사드립니다!
