### ISSUE TITLE
[5.2 객체 타입의 호환성] - 두 가지 기준 - 설명 오타

### ISSUE THREAD

**Issue by choyongjoon** [heejongahn/ts-for-jsdev#15]
https://ahnheejong.gitbook.io/ts-for-jsdev/05-type-compatibility/objects

> 타입 A와 B에 대해, A가 B에 할당 가능하려면 다음 두 기준을 만족해야 한.

"한다."가 "한."으로 오타가 난 것으로 보입니다.

**Comment by heejongahn** [comment]
감사합니다! 수정했습니다.
