### ISSUE TITLE
[5.5 제네릭의 호환성] - 모든 타입 변수가 어떤 타입인지 알려진 경우 - 코멘트 오타

### ISSUE THREAD

**Issue by choyongjoon** [heejongahn/ts-for-jsdev#16]
https://ahnheejong.gitbook.io/ts-for-jsdev/05-type-compatibility/generics

마지막 코드에서
```
y = x; // 타입 에
```

"타입 에러"가 "타입 에"로 오타가 난 것으로 보입니다.

**Comment by heejongahn** [comment]
감사합니다!
