### ISSUE TITLE
오탈자 신고

### ISSUE THREAD

**Issue by reniowood** [heejongahn/ts-for-jsdev#3]
안녕하세요,

아래 문서의 첫 번째 예제 설명에 오타가 있어 이슈 올립니다.
https://ahnheejong.gitbook.io/ts-for-jsdev/02-ecmascript/block-level-scope

해당 예제에 따르면 abc 변수 선언은 각각 2번째 줄과 4번째 줄에 있으나, 본문엔

따라서 1번 라인과 3번 라인의 abc는 동일한 변수를 가리킨다. 

라고 명시되어있습니다. 수정 부탁드립니다.

어렵게 공개해주신 문서 잘 보고 있습니다.
감사합니다.

**Comment by heejongahn** [comment]
교정 보면서 가독성을 높히기 위해 코드를 수정하고는 본문 수정을 깜빡했네요. 반영하였고, 제보 감사드립니다.
