### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by marocchino** [heejongahn/ts-for-jsdev#9]
https://github.com/heejongahn/ts-for-jsdev/blob/aca59ba1079db29e4e138a6948d864c2f4249fdf/03-basic-grammar/intersection-type.md#L67

Programmaer -> Programmer

**Comment by heejongahn** [comment]
@marocchino 이렇게 많은 제보를... 정말 감사합니다! 리포 소개에 써놨지만 Gitbook integration이 PR을 머지하면 URL이랑 페이지 소개를 날려버리는 버그가 있어서 당분간은 이슈 만들어주시면 제가 직접 반영할게요.

그런데 혹시 영어랑 한국어 중에 어느 언어를 선호하시나요?

**Comment by heejongahn** [comment]
반영했습니다.

**Comment by marocchino** [comment]
한국사람인데 아무거나 상관없죠. 🤣 

어.. 음.. 제가 영어쓰는건 그냥 전환키 누르기 힘들어서 여서요;;
